image: jakzal/phpqa:php8.1

before_script:
  - cd ${CI_PROJECT_DIR}/app && composer install

stages:
  - analyse
  - UnitTests

security-checker:
  stage: analyse
  script:
    - local-php-security-checker composer.lock
  allow_failure: true

phpstan-insights:
    stage: analyse
    script:
        - composer analyse
    allow_failure: true

phpunit:
  stage: UnitTests
  image: thecodingmachine/php:8.1-v4-fpm-node16
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: pass_test
    MYSQL_DATABASE: myapp_test
    MYSQL_USER: myapptest
    MYSQL_PASSWORD: myapptest
    DATABASE_URL: "mysql://myapptest:myapptest@mysql:3306/myapp"
  before_script:
    - cd ${CI_PROJECT_DIR}/app
    - apt-get update && apt-get install -y git libzip-dev
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls
    - php composer.phar install
    - npm --version
    - npm install
    - npm run dev
    - php bin/console doctrine:database:drop --force --env=test
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --env=test --force
    - php bin/console doctrine:fixtures:load -n --env=test
  script:
    - php bin/phpunit --colors=always
  allow_failure: false

