version : "3.8"
services:

 #Add image mysql in docker by Son Excellence WADE
  db:
    image: mysql
    container_name: db_docker_workflow
    restart: always
    volumes:
    - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev


  #Add image phpmyadmin in docker by Son Excellence WADE
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_workflow
    restart: always
    depends_on:
      - db
    ports:
    - 8000:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  #Add image maildev in docker by Son Excellence WADE
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_workflow
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  #Add image php in docker by Son Excellence WADE
  www:
    build: php
    container_name: www_docker_workflow
    ports:
      - "8082:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev


networks:
  dev:
volumes:
  db-data: